In [10]:
sayı, sayı2  = map(int, (input().split()))

liste = []

for i in range(sayı):
    a = list(map(int,input().split()))
    liste.extend(a)
np.array(liste).reshape(sayı, sayı2)

2 2
3 1
2 4


array([[3, 1],
       [2, 4]])

In [ ]:
sayı = int(input()[0])

print(sayı)
arr = np.array()
print(arr)
for i in range(sayı):
    liste = list(map(int, input().split()))
    arr += np.array(liste)

In [ ]:
np.arr

In [4]:
a = map(int,input().split())
type(a)

2 2


map

In [2]:
def prime(x):
    for i in range(2, int(x/2)):
        if x % i == 0:
            return False
    return True

In [3]:
prime(13)

True

In [ ]:
a = np.array(filter(prime, np.arange(2_000_000)))
print(sum(a))

In [9]:
(filter(prime, np.arange(2_00)))

In [10]:
np.fromiter((filter(prime, np.arange(2_00))))

TypeError: fromiter() missing required argument 'dtype' (pos 2)

In [12]:
import numpy as np

def sieve_of_eratosthenes(n):
    primes = np.ones(n+1, dtype=bool) # Numpy array oluşturun ve bütün elemanlarını True olarak ayarlayın.
    primes[0:2] = False # 0 ve 1 asal sayı olmadığından False olarak ayarlayın.
    for i in range(2, int(n**0.5)+1):
        if primes[i]:
            primes[i*i::i] = False # i'nin katlarını False olarak ayarlayın.
    return np.flatnonzero(primes) # True olarak işaretlenen bütün sayıların dizinlerini döndürün.

primes = sieve_of_eratosthenes(2000000)
print(sum(primes))


142913828922


In [11]:
i : 3 sayı : 2
        primes[9::2]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.flatnonzero()

In [3]:
arr = np.arange(60)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [6]:
arr = arr.reshape(5, 3, -1)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]],

       [[36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]]])

In [8]:
np.shape(arr)

(5, 3, 4)

In [11]:
arr = np.arange(60)
arr.reshape(2, 5, 6)

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59]]])

In [17]:
arr = np.array([1,2,0,0,4,0])
np.where((arr == 1, arr == 2, arr == 4))

(array([0, 1, 2], dtype=int64), array([0, 1, 4], dtype=int64))

In [19]:
np.where(arr in [1, 2, 4])

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [1]:
import numpy as np

In [2]:
np.arange(60).reshape(3,5,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19]]],


       [[[20, 21],
         [22, 23]],

        [[24, 25],
         [26, 27]],

        [[28, 29],
         [30, 31]],

        [[32, 33],
         [34, 35]],

        [[36, 37],
         [38, 39]]],


       [[[40, 41],
         [42, 43]],

        [[44, 45],
         [46, 47]],

        [[48, 49],
         [50, 51]],

        [[52, 53],
         [54, 55]],

        [[56, 57],
         [58, 59]]]])