In [3]:
import numpy as np

# np.flip()

arrayı tersten sıralama

In [5]:
a = np.array([4, 3, 5, 6, 1])
a

array([4, 3, 5, 6, 1])

In [6]:
np.flip(a)

array([1, 6, 5, 3, 4])

# np.flatten()

arrayı (-1) haline getirdi. yani bütün elemanları bir vektöre topladı

In [2]:
my_array = np.array([[1,2,3],
                        [4,5,6]])
my_array.flatten()


array([1, 2, 3, 4, 5, 6])

In [6]:
my_array = np.array([[1,2,3], [4,5,6]]).reshape(-1)
my_array

array([1, 2, 3, 4, 5, 6])

# np.transpose()

array'in transpozunu verir

In [12]:
my_array = np.array([[1,2,3],
                        [4,5,6]])
print(my_array)
print(np.transpose(my_array))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


# np.tile()

tile() fonksiyonu, iki parametre alır: ilki tekrarlanacak dizi veya matris, ikincisi ise tekrarlama sayısıdır. Tekrarlama sayısı, her boyuttaki tekrarlanma sayılarını belirlemek için bir demet (tuple) olarak da verilebilir.

In [1]:
a = np.array([1, 2, 3])
b = np.tile(a, 3)

print(b)

[1 2 3 1 2 3 1 2 3]


In [2]:
a = np.array([[1, 2], [3, 4]])
b = np.tile(a, (2, 3))

print(b)

[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


# np.where()

Bu fonksiyon, belirli bir koşulu sağlayan dizinin elemanlarının indekslerini veya değerlerini döndürür.

In [1]:
arr = np.array([1, -2, 3, -4, 5, -6])

positive_indices = np.where(arr > 0)
negative_indices = np.where(arr < 0)

print(positive_indices) # index numaralarını döndürdü
print(negative_indices)

(array([0, 2, 4], dtype=int64),)
(array([1, 3, 5], dtype=int64),)


In [10]:
arr = np.array([1, -2, 3, -4, 5, -6])

positive_values = np.where(arr > 0, arr, 100)
negative_values = np.where(arr < 0, arr, -100)

print(positive_values)  # negatif olan değerler yerine 100 yazdırdık
print(negative_values) # bir üstteki kod bloğundan farklı olarak burada index değerleri değil elemanların kendisi döndü

[  1 100   3 100   5 100]
[-100   -2 -100   -4 -100   -6]


# Selection on a Condition- koşullu işlemler

In [21]:
# dizideki between 3 and 8 olanları -1 ile çarptı
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr[(arr >= 3) & (arr <= 8)] *= -1
print(arr)

[ 1  2 -3 -4 -5 -6 -7 -8  9 10]


In [23]:
# dizideki 5 ten büyük eleman sayısını döndürdü
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

count = np.count_nonzero(arr > 5)

print(count)

5


In [26]:
#dizideki çift sayıların toplamını hesapladık
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
sum_val = np.sum(arr[arr % 2 == 0])

print(sum_val)

30


In [27]:
#dizideki 5 ten büyük elemanların ortalamasını hesapladı
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mean_val = np.mean(arr[arr > 5])

print(mean_val)

8.0


In [28]:
# dizideki 7 den küçük elemanlar arasındaki max
# dizideki 3 ten büyükler arasındaki min

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
max_val = np.max(arr[arr < 7])
min_val = np.min(arr[arr > 3])

print(max_val)
print(min_val)

6
4


In [30]:
#eleman 0 dan büyük ve 10 dan küçükse karesini al
arr = np.array([[2, 12, 5], [4, 8, 1]])
arr[(arr > 0) & (arr < 10)] **= 2

print(arr)
# çıktı: [[4, 0, 25], [16, 64, 1]]

[[ 4 12 25]
 [16 64  1]]


In [31]:
# 2 veya 3' e tam bölünenleri -1 ile çarp
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr[(arr % 2 == 0) | (arr % 3 == 0)] *= -1

print(arr)
# çıktı: [ 1 -2 -3 -4  5  6 -7 -8 -9 10]

[  1  -2  -3  -4   5  -6   7  -8  -9 -10]


# np.array_equal()

In [32]:

A = np.random.randint(0, 5, 5)
B = np.random.randint(0, 5, 5)

# Dizilerin eşitliğini kontrol etme
if np.array_equal(A, B):
    print("Diziler eşittir.")
else:
    print("Diziler eşit değildir.")

Diziler eşit değildir.


In [1]:
arr = np.array([0, 1, 1, 3, 2, 1, 7, 5, 4, 5, 3])

# Bincount() fonksiyonunu kullanarak her bir benzersiz değerin sayısını bulun
count = np.bincount(arr)

print(count)

[1 3 1 2 1 2 0 1]


# np.bincount()

In [2]:
arr = np.array([0, 1, 1, 3, 2, 1, 7, 5, 4, 5, 3])

# Bincount() fonksiyonunu kullanarak her bir benzersiz değerin sayısını bulun
count = np.bincount(arr)

print(count) # 0'dan 1 adet, 1'den 3 adet, 2'den 1 adet .....

[1 3 1 2 1 2 0 1]


# np.nonzero()

In [1]:
arr = np.array([[0, 1, 2], [3, 0, 5]])

# arr içinde sıfırdan farklı elemanların indislerini döndürür
nonzero_indices = np.nonzero(arr)

print(nonzero_indices)

(array([0, 0, 1, 1], dtype=int64), array([1, 2, 0, 2], dtype=int64))


# np.unravel_index()
Örneğin, bu kod np.unravel_index(100, (6,7,8)) 7 satır, 8 sütun ve 6 derinlikli bir dizi içindeki 100 numaralı elemanın indislerini hesaplar. İndisler, tuple formatında (x, y, z) olarak döndürülür.

In [2]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


# np.random.seed()

In [ ]:
# np.random.seed(42)
# np.random.seed(101)

# np.diag()

# np.corrcoef()

# np.take()