# itemsize & size

Bir dizideki toplam eleman sayısı
2x3'lük bir matris için size=6

itemsize(), NumPy dizisinin her bir elemanının bellekte kaç byte kapladığını gösterir. 
Bu özellik, NumPy dizisinin veri tipine (dtype) bağlıdır ve bu veri tipinin boyutuna göre değişir.
itemsize(), bir NumPy dizisinin bellekte kapladığı toplam alanı hesaplamak için de kullanılabilir. Bu hesaplama, dizinin eleman sayısının itemsize() ile çarpımı ile yapılabilir.
float32 tipi 32 bit (4 byte) bellek kullanır ve yaklaşık 7 basamak hassasiyetle ondalık sayıları temsil edebilir. 
32 bitlik bir sayı, 2^32 farklı sayıyı ifade edebilir.
float64 tipi ise 64 bit (8 byte) bellek kullanır ve yaklaşık 15-16 basamak hassasiyetle ondalık sayıları temsil edebilir
64 bitlik bir sayı, 2^64 farklı sayıyı ifade edebilir.

In [1]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a.size # kaç elemanı olduğunu verir

10

In [53]:
c = np.array([[0, 1], [2, 3]])
print(c.size)
c.itemsize

4


4

In [8]:
a.itemsize # bir elemanın ne kadar boyut kapladığını verir

4

In [9]:
a.size * a.itemsize # array'in toplam boyutunu hesapladık

40

# shape & reshape()

shape; Numpy array nesnesinin kaç satır ve sütundan oluştuğunu gösteren bir tupple nesnesi döndürür.

reshape; Numpy array’i yeniden şekillendirmek istediğimizde yani satır ve sütun sayısını değiştirmek istediğimizde reshape() metodunu kullanabiliriz.(orjinal matris ile istenen matris uyumlu olmalıdır)

In [16]:
liste = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
arr = np.array(liste)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [17]:
arr.shape

(4, 3)

In [20]:
arr.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
arr.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [36]:
a = arr.reshape(12).reshape(2, 6, 1) # 2 adet (6, 1) lik vektör var demek oluyor. yani 3 boyutlu
print(a)
a.shape


[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]
  [10]
  [11]
  [12]]]


(2, 6, 1)

In [33]:
a = arr.reshape(4, -1) # 4 satırlı olsun ve sütunları otomatik düzenle
print(a)
a.shape

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


(4, 3)

In [28]:
arr.reshape(-1, 2) # 2 sütunlu olsun ve satır sayısını sen ayarla

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

# resize

resize(), ndarray nesnesinin boyutunu yeniden şekillendirmek için kullanılır. 

Bu yöntem, ndarray nesnesinin boyutunu değiştirir ve yeni boyutlara uygun olarak verileri değiştirir. 

Yani, ndarray nesnesinin boyutunu değiştirmek ve verilerini yeniden boyutlandırmak istediğinizde, resize yöntemini kullanabilirsiniz. 

Ancak, bu işlem, orijinal verilerin değiştirilmesine neden olabilir, bu nedenle dikkatli kullanılmalıdır.

reshape'den farkı: reshape sadece verilen dizenin sınırlarına göre yeni array oluşturabilir
resize ise verilen dizeye uygun olmayan matrisler oluşturabilir

In [1]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
np.resize(arr, (3, 2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
np.resize(arr, (6, 3)) # arr 6 elemanlı olmasına rağmen 18 elemanlı bir array oluşturabildik

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [4]:
np.resize(arr, (2, 2))

array([[1, 2],
       [3, 4]])

In [1]:
a = np.arange(12).reshape(4, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [2]:
a.resize(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# ndmin

Bir numpy array oluşturulurken boyut sayısını belirtmek için kullanılır.

In [38]:
myList=list(range(0,48))
myArray=np.array(myList, ndmin=3)
myArray

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
         32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]]])

In [42]:
myArray.reshape(2, 4, 6)

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]]])

# ndim

array in kaç boyutlu olduğunu söyler

In [51]:
myarr.ndim

1

# dtype & astype

dtype, bir numpy dizisinin veri tipini belirlemek  ve öğrenmek için kullanılır.

astype ise, bir numpy dizisinin veri tipini dönüştürmek için kullanılır. 

In [43]:
my_int = np.array([1, 2, 3])
my_int

array([1, 2, 3])

In [44]:
my_int.dtype

dtype('int32')

In [45]:
my_float = np.array([1, 2, 3, 4.5])
my_float

array([1. , 2. , 3. , 4.5])

In [47]:
my_float.dtype

dtype('float64')

In [48]:
x = np.array([1, 2], dtype=np.float64)
print(x)        
print(x.dtype)  

[1. 2.]
float64


In [52]:
a = np.arange(10)
print(a)
new = a.astype(float)
print(new)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


# max & argmax & min & argmin

min(), bir dizinin içindeki en küçük değeri döndürür

max(), bir dizinin içindeki en büyük değeri döndürür

argmin(), bir dizinin içindeki en küçük değerin indeksini döndürür

argmax(), bir dizinin içindeki en büyük değerin indeksini döndürür

In [49]:
myarr = np.random.randint(0, 50, 10)
print(myarr)

[42 28 28 46 23 28 16  1 45 24]


In [50]:
print(myarr.max())
print(myarr.min())
print(myarr.argmax())
print(myarr.argmin())

46
1
3
7


# copy

copy(), Numpy dizilerinde bir kopya oluşturmak için kullanılır. 

Bu fonksiyon, orijinal dizinin aynısını oluşturur ancak bu kopya bağımsızdır. Yani, kopya dizisi üzerinde yapılan herhangi bir değişiklik, orijinal diziyi etkilemez ve orijinal dizi üzerinde yapılan değişiklikler de kopya dizisini etkilemez.

In [57]:
q = np.arange(15).reshape(3, 5)
print(q)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [60]:
r = q.copy()
print(r)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [61]:
q[1][2] = 100
print(q)

[[  0   1   2   3   4]
 [  5   6 100   8   9]
 [ 10  11  12  13  14]]


In [62]:
print(r)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


# transpose

transpose() fonksiyonu, NumPy dizilerinin boyutlarını değiştiren bir işlevdir. Özellikle matrislerin transpozunu almak için kullanılır.

Bir matrisin transpozunu almak, matrisin satırlarını sütunlarına, sütunlarını da satırlarına dönüştürür.

In [63]:
r

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [65]:
r.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

# create array methods

## array()

In [9]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [14]:
liste = [0.3, 0.5, 1, 1.5]
np.array(liste)

array([0.3, 0.5, 1. , 1.5])

## asarray()

In [15]:
arr2 = np.asarray(liste)
arr2

array([0.3, 0.5, 1. , 1.5])

## arange()

In [16]:
np.arange(5)

array([0, 1, 2, 3, 4])

## fromiter()

fromiter(), bir array oluşturmak için bir iterator nesnesinden verileri alır.

Verilerin bellekte tutulmasına gerek kalmadan, yineleyiciden elemanları tek tek çekerek NumPy dizisine dönüştürür. 

Bu özellikle büyük verilerle çalışırken bellek kullanımını azaltmak için yararlıdır.

In [37]:
iter_obje = (i for i in range(5))
iter_obje

<generator object <genexpr> at 0x000001F02E4EF140>

In [38]:
c = np.fromiter(iter_obje, int)
print(c)


[0 1 2 3 4]


In [5]:
iter2 = ((x, x) for x in range(5))
a = np.fromiter(iter2, dtype = (int, 2)) # her iki elemanda int demek için 2 yazdık
print(a)

[[0 0]
 [1 1]
 [2 2]
 [3 3]
 [4 4]]


## linspace()

np.linspace(start, stop, num=50(default))

Verilen başlangıç ve bitiş değerleri arasında, belirtilen sayıda eşit aralıklı değerlerden oluşan bir numpy dizisi oluşturur.

Bu fonksiyon, özellikle grafik çizme ve veri analizi gibi durumlarda yararlıdır.

In [38]:
np.linspace(0, 20)

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

In [40]:
np.linspace(0, 20, 5)

array([ 0.,  5., 10., 15., 20.])

In [41]:
np.linspace(0, 20, 5, retstep=True) # retstep: aralık değerini döndürdü

(array([ 0.,  5., 10., 15., 20.]), 5.0)

In [43]:
np.linspace(0, 20, 5, endpoint=False) # endpoint : son değeri dahil etmedi

array([ 0.,  4.,  8., 12., 16.])

In [44]:
np.linspace(0, 20, 5, dtype=int) # dtype : veri türünü belirleyebiliriz

array([ 0,  5, 10, 15, 20])

In [45]:
np.linspace(0, [10, 20], 5, axis = 1 ) # axis1 satır yönünü ifade ettiği için

array([[ 0. ,  2.5,  5. ,  7.5, 10. ],
       [ 0. ,  5. , 10. , 15. , 20. ]])

In [6]:
np.linspace(0, [10, 20], 5 ) # axis default 0'dır

array([[ 0. ,  0. ],
       [ 2.5,  5. ],
       [ 5. , 10. ],
       [ 7.5, 15. ],
       [10. , 20. ]])

In [47]:
np.linspace(0, [10, 20], 5, axis = 0 ) # axis0 sütun yönünü ifade ettiği için

array([[ 0. ,  0. ],
       [ 2.5,  5. ],
       [ 5. , 10. ],
       [ 7.5, 15. ],
       [10. , 20. ]])

## logspace()

np.logspace(start, stop, base = 10(default), num = 50(default))

logspace() logaritmik aralıklarda bir dizi oluşturur. 

logspace() fonksiyonu, linspace() fonksiyonuna benzer şekilde çalışır, ancak aralıklar logaritmik olarak hesaplanır.



In [51]:
np.logspace(2, 3 , num=10) # 10 üzeri 2 ve 10 üzeri 3 aralığında 10 adet eleman oluşturdu

array([ 100.        ,  129.1549665 ,  166.81005372,  215.443469  ,
        278.25594022,  359.38136638,  464.15888336,  599.48425032,
        774.26368268, 1000.        ])

In [61]:
np.logspace(2, 3 , num=10, base=2)  # 2 üzeri 2 ve 2 üzeri 3 aralığında 10 adet eleman oluşturdu

array([4.        , 4.32023896, 4.66611616, 5.0396842 , 5.44316   ,
       5.87893797, 6.34960421, 6.85795186, 7.4069977 , 8.        ])

## zeros & zeros_like

Belirtilen satır ve sütuna sahip 0'lardan oluşan bir matris döndürür.

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.zeros_like(arr.reshape(5,2)) # arr isimli arrayi (5, 2) formatına çevirip bütün elemanlarını 0 yaptık

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

## ones & ones_like

Belirtilen satır ve sütuna sahip 1'lerdan oluşan bir matris döndürür.

In [15]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [17]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.ones_like(arr)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [19]:
arr * 5 # bütün elemanları 5 ile çarptı

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [20]:
arr + 5 # bütün elemanlara 5 ekledi

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## eye

Belirlenen boyutlarda diagonel 1 olacak şekilde matris oluşturmamızı sağlayan fonksiyon.

In [24]:
np.eye (3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.eye (3, 3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

## full & full_like

Sabit sayıdan oluşan matris oluşturur

In [28]:
np.full((3, 3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [29]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.full_like(arr, -3)

array([-3, -3, -3, -3, -3, -3, -3, -3, -3, -3])

## random.rand()

0-1 aralığında random float sayılar üretir.

In [31]:
np.random.rand(3, 3) # 0 ile 1 arasında değerler üretti

array([[0.3746789 , 0.41345879, 0.26137392],
       [0.29000403, 0.91737184, 0.30105358],
       [0.43398266, 0.57426345, 0.08514068]])

## random.randn()

ortalama değeri 0 ve standart sapması 1 olan normal dağılıma sahip rastgele sayılar üretmek için kullanılır. 

Fonksiyon, normal dağılımdan rastgele sayılar üretir ve bu sayıları NumPy dizisi olarak döndürür.

In [32]:
np.random.randn(3, 3) 

array([[-1.41780388,  0.25077943,  0.79689107],
       [-1.76489067,  0.96787697, -0.09684995],
       [ 1.01231285, -0.56211953,  0.03939278]])

## random.randint()

0-100 aralığında integer değerler üretir

Bitiş(100) dahil değil

In [33]:
np.random.randint(10) # 0 ile 10 arasında bir sayı üretti

5

In [35]:
np.random.randint(10, size = (3, 3))

array([[8, 1, 3],
       [8, 6, 7],
       [3, 4, 7]])

# concatenate()

concatenate() fonksiyonu, iki veya daha fazla diziyi birleştirmek için kullanılır. 

Fonksiyonun ilk parametresi birleştirilecek dizilerin bir listesidir. 

İkinci parametre ise, birleştirme işleminin hangi eksen veya boyuta göre yapılacağını belirten bir parametredir.

Örneğin, axis=0 parametresi, dizilerin satır bazında (dikey birleştirme) birleştirilmesini, axis=1 parametresi ise sütun bazında (yatay birleştirme) birleştirilmesini sağlar.[numpy.concatenate 01](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html),
[numpy.concatenate 02](https://sparkbyexamples.com/numpy/numpy-concatenate-arrays/),
[numpy.concatenate 03](https://www.tutorialspoint.com/numpy/numpy_concatenate.htm),
[numpy.concatenate 04](https://www.w3resource.com/numpy/manipulation/concatenate.php)

In [1]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [2]:
x + y

array([5, 7, 9])

In [3]:
np.concatenate((x, y))

array([1, 2, 3, 4, 5, 6])

In [4]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [5]:
a + b

array([[ 6,  8],
       [10, 12]])

In [6]:
np.concatenate((a, b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [7]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [8]:
np.concatenate((a, b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# split() & array_split() & hsplit() & vsplit()

split(), numpy dizisini belirtilen eksende eşit parçalara bölmek için kullanılır.
[numpy.split 01](https://www.w3resource.com/numpy/manipulation/split.php),
[numpy.split 02](https://sparkbyexamples.com/numpy/numpy-split-array/),
[numpy.split 03](https://numpy.org/doc/stable/reference/generated/numpy.array_split.html),
[numpy.split 04](https://www.w3schools.com/python/numpy/numpy_array_split.asp)

In [9]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
np.split(a, 4)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

In [15]:
np.split(a, [4]) # 4. indexe kadar bir parça sonrası bir parça

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]

In [16]:
np.split(a, [2])

[array([1, 2]), array([3, 4, 5, 6, 7, 8])]

In [17]:
x = np.arange(20).reshape(5, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [18]:
np.split(x, [1, 3])

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [20]:
np.split(x, [1, 3], axis=1)

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [19]:
np.split(x, [1, 3, 4], axis=0)

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [21]:
np.hsplit(x, [1, 3]) # axis = 1 olarak işlem yapar

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [22]:
np.vsplit(x, [1, 3]) # axis = 0 olarak işlem yapar

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [13]:
np.array_split(a, 3)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]

# sort()

sort(), numerik ya da alfabetik array elemanlarını, numerik veya alfabetik sıralarına göre sıralamasını yapar.
[numpy.sort 01](https://www.w3schools.com/python/numpy/numpy_array_sort.asp),
[numpy.sort 02](https://sparkbyexamples.com/python/numpy-sort-arrays-examples/),
[numpy.sort 03](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.sort.html),
[numpy.sort 04](https://www.geeksforgeeks.org/how-to-sort-a-numpy-array-python/)

In [23]:
a = np.array([2, 1, 4, 3, 5])
a

array([2, 1, 4, 3, 5])

In [24]:
a.sort()
a

array([1, 2, 3, 4, 5])

In [25]:
b = np.random.randint(5, 100, (3, 3))
b

array([[32, 33, 18],
       [56, 47, 27],
       [ 9, 89, 26]])

In [26]:
np.sort(b, axis=0)

array([[ 9, 33, 18],
       [32, 47, 26],
       [56, 89, 27]])

In [27]:
np.sort(b, axis=1)

array([[18, 32, 33],
       [27, 47, 56],
       [ 9, 26, 89]])

In [31]:
b.sort()
b

array([[18, 32, 33],
       [27, 47, 56],
       [ 9, 26, 89]])

In [32]:
np.sort(b, axis=None)

array([ 9, 18, 26, 27, 32, 33, 47, 56, 89])

# index % slice

NumPy dizilerinde belirli bir elemana erişmek için, dizi adını takiben köşeli parantez içinde ilgili elemanın indeks numarasını belirtiriz.Örn; myarr[indexno]

İndeks numaraları 0'dan başlar, yani ilk elemanın indeksi 0'dır ve diğer elemanların indeks numaraları sırasıyla 1, 2, 3, gibi artar.

Ayrıca negatif indeksleme de kullanabiliriz. Negatif indeksleme, NumPy dizilerinde sondan başlayarak elemanlara erişmek için kullanılır. Son elemanın indeksi -1'dir ve önceki elemanların indeksleri sırayla -2, -3, gibi devam eder.

2 boyutlu NumPy dizilerinde, belirli bir elemana erişmek için satır ve sütun numaralarını kullanırız. Bu şekilde erişim için myarr[satırno, sütunno] formatı kullanılır.

3 boyutlu NumPy dizilerinde ise, elemana erişmek için derinlik, satır ve sütun numaralarını kullanırız. Yani erişim için myarr[derinlikno, satırno, sütunno] formatı kullanılır.

[INDEXING & SLICING Source 01](https://jakevdp.github.io/PythonDataScienceHandbook/03.02-data-indexing-and-selection.html),
[INDEXING & SLICING Source 02](https://www.kite.com/python/answers/how-to-select-an-element-by-index-from-a-numpy-array-in-python),
[INDEXING & SLICING Source 03](https://www.w3schools.com/python/numpy/numpy_array_indexing.asp),
[INDEXING & SLICING Source 04](https://www.pluralsight.com/guides/working-numpy-arrays-indexing-slicing-guide),
[INDEXING & SLICING Source 05](https://www.brainstobytes.com/hands-on-numpy-iii-indexing-and-slicing/),
[INDEXING & SLICING Source 06](https://www.geeksforgeeks.org/numpy-indexing/),
[INDEXING & SLICING Source 07](https://www.tutorialspoint.com/numpy/numpy_advanced_indexing.htm),
[INDEXING & SLICING Source 08](https://towardsdatascience.com/numpy-indexing-explained-c376abb2440d),
[INDEXING & SLICING Video Source 01](https://www.pythoninformer.com/python-libraries/numpy/index-and-slice/),
[INDEXING & SLICING Video Source 02](https://www.youtube.com/watch?v=9nbBTaz2qXI),
[INDEXING & SLICING Video Source 03](https://www.youtube.com/watch?v=E1OFcMnU40o)

## Bracket Indexing & Selection

In [35]:
arr = np.arange(1, 24)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23])

In [36]:
arr[4]

5

In [37]:
arr[4:10]

array([ 5,  6,  7,  8,  9, 10])

In [38]:
arr[::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [39]:
arr[1::2]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

## Indexing & Slicing a 2D Array (Matrices)

![image-2.png](https://i.ibb.co/64DGhj7/Numpy-index.jpg)

[SOURCE](https://stackoverflow.com/questions/16096753/python-array-slicing-how-can-2d-array-slicing-be-implemented)

![image.png](https://i.ibb.co/xmcGm9C/numpy-index1.png)

[SOURCE](https://scipy-lectures.org/intro/numpy/array_object.html)

[SOURCE](http://cs-tklab.na-inet.jp/~tkouya/python/scipy-lectures/intro/numpy/array_object.html)

![image-2.png](https://i.ibb.co/bHYsGLb/numpy-indexing-1.png)

In [41]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
arr_2d[1]

array([4, 5, 6])

In [45]:
arr_2d[1][2]

6

In [46]:
arr_2d[1][-1]

6

In [47]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
arr_2d[0:2, 1:]

array([[2, 3],
       [5, 6]])

In [49]:
arr_2d[2]

array([7, 8, 9])

In [51]:
arr_2d[2:]

array([[7, 8, 9]])

In [55]:
arr_2d[:, 1]

array([2, 5, 8])

In [56]:
arr_2d[:, 1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [58]:
arr_2d[1, 1]

5

## Fancy Indexing

Fancy Indexing, NumPy dizilerinde, bir veya daha fazla koşula veya belirtilen indeksler listesine göre dizideki belirli elemanlara erişmek için kullanılan bir indeksleme yöntemidir.

Bu yöntemde, köşeli parantez içinde bir liste veya dizi kullanarak, ilgili dizinin belirli elemanlarına erişebilirsiniz. Bu indeksleme yöntemi, normal indeksleme yöntemlerine göre daha esnek ve güçlüdür.

[SOURCE 01](https://jakevdp.github.io/PythonDataScienceHandbook/02.07-fancy-indexing.html#:~:text=Fancy%20indexing%20is%20conceptually%20simple,random.),
[SOURCE 02](https://notes.tahamaddam.com/coding/numpy/numpy-fancy-indexing), 
[SOURCE 03](https://stackoverflow.com/questions/52485840/numpy-fancy-indexing-with-tuples?rq=1),
[VIDEO SOURCE](https://www.youtube.com/watch?v=WpXH4PzDtYA)

In [59]:
a = np.arange(0, 30, 3)
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [61]:
[a[1], a[3], a[5]]

[3, 9, 15]

In [62]:
a[[1, 3, 5]]

array([ 3,  9, 15])

In [63]:
arr = np.arange(100).reshape(10,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [64]:
arr[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
arr[[0, 2, 4, 6, 8]]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [68]:
arr[[0, 2, 4, 6, 8], [0]]

array([ 0, 20, 40, 60, 80])

In [67]:
arr[0, 1]

1

In [70]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [69]:
arr[[1, 2], [0, 3]] # arr[1][0] ve arr[2][3] demek oldu

array([10, 23])

In [71]:
arr[[0, 2, 3], [0, 1, 3]]

array([ 0, 21, 33])

In [72]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [73]:
arr[1, [1, 3]]

array([11, 13])

In [74]:
arr[[0, 9], 1]

array([ 1, 91])

In [75]:
arr[:, [8, 9]]

array([[ 8,  9],
       [18, 19],
       [28, 29],
       [38, 39],
       [48, 49],
       [58, 59],
       [68, 69],
       [78, 79],
       [88, 89],
       [98, 99]])

In [76]:
arr[1:3, [1, 2]]

array([[11, 12],
       [21, 22]])

In [78]:
arr[1:3, 1:3]

array([[11, 12],
       [21, 22]])

## Selection on a Condition

In [79]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [83]:
arr[arr > 4] # 4. indexten sonrasını getirdi

array([ 5,  6,  7,  8,  9, 10])


# Broadcasting

Broadcasting, farklı şekillerdeki (shape) NumPy dizileri üzerinde aritmetik işlemler yapmak için kullanılan bir özelliktir.

Bu özellik, işlem yapmak için iki dizinin şekillerinin tam olarak eşleşmesi gerektiği durumlarda, NumPy'nin işlemi otomatik olarak yürüterek daha esnek bir şekilde işlem yapılmasını sağlar.

Broadcasting işlemi, daha küçük boyutlu bir dizi ile daha büyük boyutlu bir dizi arasında gerçekleştirilir. 

Bu işlemde, daha küçük boyutlu dizi, diğer diziye uyarlanarak işlem yapılabilir hale getirilir.

In [1]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
arr[:5]

array([1, 2, 3, 4, 5])

In [3]:
arr[:3] = 11
arr

array([11, 11, 11,  4,  5,  6,  7,  8,  9, 10])

In [6]:
sliceofarr = arr[3: 7]
sliceofarr

array([4, 5, 6, 7])

In [7]:
sliceofarr[:] = 99
sliceofarr

array([99, 99, 99, 99])

In [8]:
arr # orjinal dizide etkilendi


array([11, 11, 11, 99, 99, 99, 99,  8,  9, 10])

# Arithmetic Operations

Arithmetic Operations, NumPy dizileri üzerinde aritmetik işlemler yapmak için kullanılan işlevlerdir. 

Matematiksel işlemleri vektörize ederek, for döngüleri gibi yavaş işlemlerden kaçınarak hızlı ve etkili hesaplamalar yapılmasını sağlar.

Toplama, çıkarma, çarpma, bölme, üs alma, karekök alma ve benzeri birçok aritmetik işlemi destekler. 

Farklı boyutlarda ve şekillerdeki NumPy dizileri üzerinde uygulanabilir.

In [9]:
arr2 = np.arange(1,10)
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr2 + arr2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
arr2 - arr2

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
arr2 * arr2

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [13]:
arr2 / arr2

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Universal Array Functions

Universal Array Functions (Ufuncs)(Evrensel Dizi Fonksiyonları), NumPy dizileri üzerinde hızlı ve etkili matematiksel işlemleri yapmak için kullanılan işlevlerdir. Bu işlevler, özellikle büyük veri setleri üzerinde hızlı hesaplamalar yapmak için tasarlanmıştır.

Ufuncs işlevleri, matematiksel işlemleri vektörize etmek için kullanılabilir. Bu sayede, for döngüleri ve benzeri işlemlerle uğraşmadan, NumPy dizilerinde hızlı işlemler gerçekleştirmek mümkündür.

NumPy Ufuncs işlevleri arasında, trigonometrik işlemler (sin, cos, tan vb.), logaritmik işlemler (log, exp vb.), aritmetik işlemler (toplama, çıkarma, çarpma, bölme vb.) gibi birçok işlev bulunur. Bu işlevler, farklı boyutlarda ve şekillerdeki NumPy dizileri üzerinde kullanılabilir.

[universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html)

In [14]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.subtract(arr2, 2) # çıkarma işlemi. tüm elemanlardan 2 çıkardı

array([-1,  0,  1,  2,  3,  4,  5,  6,  7])

In [16]:
np.add(arr2, 5) # toplama işlemi. tüm elemanlara 5 ekledi

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
np.divide(arr2, 2) # bölme işlemi. bütün elemanları 2 ye böldü

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [18]:
np.multiply(arr2, 3) # çarpma işlemi. bütün elemanları 3 ile çarptı

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [19]:
np.power(arr2, 3) # üst alma. tüm elemanların 3. kuvvetini aldı

array([  1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [20]:
np.mod(arr2, 2) # modulüs işlemi yaptı. tüm elemanların 2 ye bölümünden kalanları aldı

array([1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [25]:
a = np.arange(-5, 0)
print(a)
np.absolute(a)   # tüm elemanların mutlak değerinin aldı

[-5 -4 -3 -2 -1]


array([5, 4, 3, 2, 1])

In [26]:
np.sqrt(arr2) # karekök alma. bütün elemanların karakökünü aldı

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [27]:
np.sin(arr2) # sinüsünü hesapladı

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

# Statistical Calculations

NumPy, veriler üzerinde istatistiksel hesaplamalar yapmak için kullanılan bir kütüphanedir. 

Verilerin ortalaması, medyanı, standart sapması, varyansı, korelasyon katsayısı, kovaryans, histogram, maksimum ve minimum değerler gibi birçok istatistiksel hesaplama işlemi yapılmasını sağlar.

Veri setlerinin hızlı bir şekilde analiz edilmesine yardımcı olur. Ayrıca, verilerin dağılımı hakkında bilgi edinmek, anormal değerlerin tespit edilmesi, verilerin normal dağılım gösterip göstermediğini kontrol etmek gibi amaçlar için de kullanılır.

[SOURCE01](https://data-flair.training/blogs/numpy-statistical-functions/),  
[SOURCE02](https://numpy.org/doc/stable/reference/routines.statistics.html), 
[SOURCE03](https://www.tutorialspoint.com/numpy/numpy_statistical_functions.htm), 
[SOURCE04](https://www.i2tutorials.com/numpy-tutorial/numpy-statistical-functions/), 
[SOURCE05](https://towardsdatascience.com/use-numpy-for-statistics-and-arithmetic-operations-in-2020-2e157b784df4), 
[SOURCE06](https://cloudxlab.com/assessment/displayslide/2509/numpy-mathematical-and-statistical-functions-on-numpy-arrays), [SOURCE07](https://stackoverflow.com/questions/63888139/calculating-some-statistics-for-each-column-of-a-numpy-ndarray), [SOURCE08](https://www.codecademy.com/learn/intro-statistics-numpy)

In [28]:
a = np.array([1, 1, 2, 2, 3, 3, 3, 4])

In [29]:
np.mean(a) # ortalamayı hesapladı

2.375

In [31]:
np.average(a) # ortalamayı hesapladı

2.375

In [32]:
np.median(a) # ortanca değer

2.5

In [33]:
a.std() # standart sapmayı hesapladı

0.9921567416492215

In [36]:
a.var() # varyansı hesaplar

0.984375

In [37]:
np.ptp(a) # max değer - min değer

3

# chatgpt entegrasyon

In [ ]:
pip install requests

In [38]:
def chatGPT(text):
    url = "https://api.openai.com/v1/completions"
    headers = {
    "Content-Type": "application/json",
    "Authorization": "Bearer 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", # bearer'dan sonra
    }
    data = {
    "model": "text-davinci-003",
    "prompt": text,
    "max_tokens": 4000,
    "temperature": 1.0,
    }
    response = requests.post(url, headers=headers, json=data)
    output = response.json()['choices'][0]['text']
    return print(output)

In [ ]:
chatGPT("requests kütüphanesi nedir ?")